### PR TITLE
Update hardware info for 5A-75B V8.2

### PR DESCRIPTION
**Pull request by vincentbaeten**
I recently ordered the colorlight 5A-75B to play around with and got a v8.2. I've updated the the hardware info with the correct components but I haven't had time to check the connections to the FPGA if they are still the same. I have noticed that the 1.0 v rail seems to be gone now. I am not sure for what or if it was used in the older versions.

### CODE REVIEW

**Comment by faber33** [comment]
I also received the v8.2 board ... ehh the Chinese sends a random version every time

**Comment by Hoernchen** [comment]
fyxi, my 8.2 board has a 6 speed grade, not 7.

**Comment by rowanG077** [comment]
The RTL8111FP is the same as the RTL8111FD with the exception that it does not support 10M and 100M only 1000M speed is supported.

**Comment by tomverbeure** [comment]
Thanks!

**Pull request merged**
