### PR TITLE
Add documentation for 5A-75B V8.0 board 

### PR DESCRIPTION
**Pull request by tpourcelot**
Hi,
I recently ordered a 5A-75B and got a new revision: V8.0.

This model seems to have only one 2MB SDRAM chip, but is otherwise very similar to the others 5A-75B boards.

I also runned pin-scan to map some of the output pins, but the mapping of SPI, SDRAM or PHY's pinouts is still in progress and are untested.

Thanks for all the previous work which allowed me to test this very quickly :)

### CODE REVIEW

**Comment by erwin3169** [comment]
Thanks for starting with the documentation of the v8 revision of the board. When examining it, I found the following:
1) The button is not located at M13 (as with v7), at least I can not get it to work.
2) J1 pin 8 (hub75 E) is assigned to E3, but on all other connectors to N4.
3) J8 pin 7 is assigned to N5, but that port is already assigned to hub75 A. If I had to make a guess, I think B15 would be a likely candidate.

**Comment by msvisser** [comment]
I've been looking at the v8 revision myself, since that is what I got when I ordered the board. And there are indeed some errors in your documentation.

1. The pinout on J1 is not completely correct, pin 6 should be F5, pin 7 should be E3 and pin 8 should be N4. This is the result with my board at least. With pin 8 as N4 it also correctly matches all the other connectors for pin 8-15.
2. The pinout on J8 is not completely correct, pin 7 should be B15, as @erwin3169 mentioned in their comment.
3. The button is located at pin R7. I found this by trial and error looking at where the connection should approximately be.
4. I do not agree with @erwin3169 on the polarity of the LED. As far as I can tell the LED is still active low.

Hopefully these comments are helpful for improving the documentation

**Comment by erwin3169** [comment]
I think setting M13 to input has caused the LED to become active high, because after changing the button port to R7 the LED is indeed active low again. Pretty weird. Thanks @msvisser.

**Comment by tpourcelot** [comment]
Hi @erwin3169 and @msvisser , thank you for your feedback on this revision.

It indeed contained some errors =(

> 1. The button is not located at M13 (as with v7), at least I can not get it to work.

The button  seems to be located at R7 as indicated by @msvisser 

> 2. J1 pin 8 (hub75 E) is assigned to E3, but on all other connectors to N4.

Corrected, J1 pin 8 is assigned to N4 similarly to all others connectors.

> 3. J8 pin 7 is assigned to N5, but that port is already assigned to hub75 A. If I had to make a guess, I think B15 would be a likely candidate.

B15 was indeed a good guess (checked with pin-scan)

> 1. The pinout on J1 is not completely correct, pin 6 should be F5, pin 7 should be E3 and pin 8 should be N4. This is the result with my board at least. With pin 8 as N4 it also correctly matches all the other connectors for pin 8-15.

It is now corrected

> 2. The pinout on J8 is not completely correct, pin 7 should be B15, as @erwin3169 mentioned in their comment.

Also corrected

> 3. The button is located at pin R7. I found this by trial and error looking at where the connection should approximately be.

Confirmed with pin-scan

> Hopefully these comments are helpful for improving the documentation

They were very useful, thank you both!

**Comment by msvisser** [comment]
I have found some more connections, this time for the ethernet PYHs.
- MDC is on R5
- MDIO is on T4
- PHYRSTB is on R6
These three connections are shared for both of the PHYs, so lowering the PHYRSTB line will reset both PHYs. The management interface over MDC/MDIO can access the registers for both PHYs by addressing them with address 1 and 2.

**Comment by Disasm** [comment]
Hi! Could you check/confirm that the JTAG pinout is correct? JTAG pins are backwards-numbered on this version of the board.

**Pull request merged**
